Revert phpdoc type for class name argument
doctrine/persistence pull request #111
Opened 2020-05-13 15:13 UTC by andrew-demb

Follow the discussion in https://github.com/doctrine/persistence/pull/104/files#r424181523

2020-05-13 15:52 UTC, alcaeus requested changes

2020-05-13 15:52 UTC, alcaeus commented on lib/Doctrine/Persistence/ObjectManager.php
> +     *
Can you add back the `@return` as well?

2020-05-13 16:15 UTC, greg0ire approved these changes

2020-05-13 21:29 UTC, SenseException approved these changes

2020-05-14 08:21 UTC, alcaeus approved these changes

2020-05-14 08:24 UTC, merged

2020-05-14 08:24 UTC, alcaeus commented
Thanks @andrew-demb!