Fix bug in namespace check in MappingDriverChain
doctrine/persistence pull request #341
Opened 2023-12-14 23:36 UTC by ttk

This fix improves the checking if a namespace appears in a className by ensuring that the namespace ends in a `\`.  Prior to this fix, the following would occur:

A className such as `Doctrine\Tests\Persistence\Mapping\DriverChainEntity` would match the namespace: `Doctrine\Tests\Persistence\Map`, which isn't correct.

Other considerations:  
- what if the namespace already ends in a `\`?  is this a valid case? Probably not.
- what if it's a parent namespace.  In the above example, this would be `Doctrine\Tests\Persistence`.  Should this match against the className `Doctrine\Tests\Persistence\Mapping\DriverChainEntity` or not?  The current logic would match, but I'm not sure if it should....

2023-12-17 19:26 UTC, malarzm requested changes

2023-12-17 19:26 UTC, malarzm commented on src/Persistence/Mapping/Driver/MappingDriverChain.php
> +            if (strpos($className, $namespace . '\\') === 0) {
The `$namespace` can already contain a `\` at the end. It'd be better to ensure there's always a single `\` at the end in the `addDriver` method

2023-12-18 06:03 UTC, derrabus commented
Please add a test.

2023-12-19 17:22 UTC, ttk commented
The namespace matching code has been revised and a new unit test added.  Note that in the current implementation, the class name will only match the namespace if it's a direct parent namespace.  ie.

`A\B\Classname`  matches `A\B` but not `A`.  I think this is ok because otherwise the wrong driver can be selected if a more global namespace appears first in the list.

2023-12-20 11:34 UTC, stof commented
This is not good IMO. Drivers currently support organizing entities in sub-namespaces. The chain driver should not restrict that more

2023-12-20 12:20 UTC, derrabus commented on tests/Persistence/Mapping/DriverChainTest.php
> +        $chain->addDriver($driver1, 'Doctrine\Tests\Persistence\Map');
What's the reason for this change?

2023-12-20 12:20 UTC, derrabus commented on tests/Persistence/Mapping/DriverChainTest.php
> +                ->will(self::returnValue(['Doctrine\Tests\Models\Company\Foo', 'Doctrine\Tests\Models\Company2\Foo']));
Same question, why did this test need an adjustment?

2023-12-20 12:20 UTC, derrabus commented on tests/Persistence/Mapping/DriverChainTest.php
> +        self::assertFalse($mdc::isMatchingNamespace($className, 'Doctrine\Tests\Persistence'));
Those tests don't tell me what problem you're attempting to solve. You're merely testing an internal function, an implementation detail.

2024-05-17 19:27 UTC, greg0ire commented
No answer… let's close this I guess.

2024-05-17 19:27 UTC, closed without merging

2024-05-17 22:08 UTC, ttk commented
This is still a issue.  Feel free to fork the branch and update it as necessary.

In the meantime, I worked around this bug by changing the name of my directory for the mapping:
Before, which didn't work because the `App` mapping would always be selected:
```
        mappings:
            App:
                dir: '%kernel.project_dir%/src/Entity'
                ...
            AppStatic:
                dir: '%kernel.project_dir%/src/EntityStatic'
                ...
```
to this, which worked, because of the unique prefix:

```
        mappings:
            App:
                dir: '%kernel.project_dir%/src/Entity'
                ...
            AppStatic:
                dir: '%kernel.project_dir%/src/StaticEntity'
                ...
```