Bugfix: Parent methods in extended EnumReflectionProperty didn't work.
doctrine/persistence pull request #342
Opened 2024-02-27 10:44 UTC by luzrain

EnumReflectionProperty extends ReflectionProperty without ReflectionProperty::__constructor() call making it impossible to use parent methods such as ReflectionProperty::getAttributes() and others.

2024-02-27 14:40 UTC, derrabus requested changes
Not calling the parent constructor was on purpose because this class is meant to be a decorator. Calls to methods like the ones you mentioned should be proxied to `$this->originalReflectionProperty` instead. We apparently had no need for them yet, but I'd happily merge any PR that adds those two methods to the `EnumReflectionProperty` class.

2024-02-27 15:04 UTC, luzrain commented
If it is a decorator, then it should implement [all parent methods](https://www.php.net/manual/en/class.reflectionproperty.php), not just the two I mentioned. Without them, EnumReflectionProperty is inconsistent, and calling any of the parent methods will throw an exception, affecting third-party software that relies on the ReflectionProperty interface (this is what I encountered with).

I've seen the same solution in Doctrine ORM [ReflectionEnumProperty.php](https://github.com/doctrine/orm/pull/9381/files#diff-560209353a914c4b5fe327c7a69e93f0507c221cc673c98b7a4bf4e81f09f9c0) and it was accepted.  
I think it would be completely sufficient in this case.

2024-02-27 15:25 UTC, derrabus commented
> If it is a decorator, then it should implement [all parent methods](https://www.php.net/manual/en/class.reflectionproperty.php), not just the two I mentioned.

Yes, it's currently incomplete.

> Without them, EnumReflectionProperty is inconsistent,

Your change makes it an inconsistent decorator.

> affecting third-party software that relies on the ReflectionProperty interface (this is what I encountered with).

Can you elaborate on this? I'm having a hard time finding out where this class is actually used.

> I've seen the same solution in Doctrine ORM [ReflectionEnumProperty.php](https://github.com/doctrine/orm/pull/9381/files#diff-560209353a914c4b5fe327c7a69e93f0507c221cc673c98b7a4bf4e81f09f9c0) and it was accepted. I think it would be a completely sufficient solution in this case.

I think, this change was okay-ish for the ORM because it's an internal class there. I would evaluate it differently for this library.

The existence of a `EnumReflectionProperty` in the ORM codebase makes me question even more why Persistence ships this class at all. We should either make the ORM leverage `EnumReflectionProperty` from Persistence or kill the Persistence version. WDYT @greg0ire?

2024-02-27 15:44 UTC, luzrain commented
> Can you elaborate on this? I'm having a hard time finding out where this class is actually used.

I encountered with issues trying to dump entity fetched by MongoDB ODM in symfony dumper.  
I'm not sure about how it is constructed internally but the error I faced with came from [here](https://github.com/symfony/var-dumper/blob/e03ad7c1535e623edbb94c22cc42353e488c6670/Caster/ReflectionCaster.php#L308).  
ReflectionCaster::castProperty() method relies on ReflectionAttribute which is not properly decorated by EnumReflectionProperty and throws an exception when symfony dumper tryin to get access to ReflectionProperty methods.

> I think, this change was okay-ish for the ORM because it's an internal class there. I would evaluate it differently for this library.

Isn't it internal as well?

2024-02-27 15:56 UTC, derrabus commented
> > Can you elaborate on this? I'm having a hard time finding out where this class is actually used.
> 
> I encountered with issues trying to dump entity fetched by MongoDB ODM in symfony dumper.

Okay, so the ODM _does_ use it. That answers my question.

> the error I faced with came from [here](https://github.com/symfony/var-dumper/blob/e03ad7c1535e623edbb94c22cc42353e488c6670/Caster/ReflectionCaster.php#L308). ReflectionCaster::castProperty() method relies on ReflectionProperty which is not properly decorated by EnumReflectionProperty and throws an exception when symfony dumper tryin to get access to ReflectionProperty methods.

Right, we should fix the decorator then.

> > I think, this change was okay-ish for the ORM because it's an internal class there. I would evaluate it differently for this library.
> 
> Isn't it internal as well?

It's not internal to the persistence library, no.

2024-02-27 16:43 UTC, greg0ire commented
> The existence of a EnumReflectionProperty in the ORM codebase 

`git log -S EnumReflectionProperty` yields nothing when run from the ORM repository, so… not sure what you are talking about :sweat_smile: 

EDIT: Ah, it's called one way in the ORM, and the other way in persistence :sweat_smile: 


The ORM class was added in https://github.com/doctrine/orm/pull/9304
The persistence class was added in https://github.com/doctrine/persistence/pull/248, the stated goal is to reduce duplication, so… yeah :rofl:

2024-02-28 04:43 UTC, luzrain commented
So what is the conclusion? How do you see the solution?
Redefining all of the methods of ReflectionProperty does not seem to be a good option either, because the list of available methods varies in different php versions (7.4, 8.0, 8.1) ,and since this package supports php >= 7.2, we should deal with it somehow.

2024-03-01 10:13 UTC, derrabus commented
> So what is the conclusion? How do you see the solution?

Let's add the missing proxy methods that we need. Alternatively, we could consider patching `VarDumper` to not treat this `EnumReflectionProperty` like an actual `ReflectionProperty` from PHP core.

2024-03-18 12:59 UTC, mustanggb commented
I've also encounted this with the same use-case as: https://github.com/doctrine/persistence/pull/342#issuecomment-1966856699 
(Symfony VarDumper of MongoDB ODM object with an Enum field)

Spits out the error: `Internal error: Failed to retrieve the reflection object`

Confirming this merge request does "fix" it, albeit sounds like not in the best way.

2024-03-18 13:38 UTC, malarzm commented
> I also tried adding the getDocComment and getModifiers methods, which I think is what https://github.com/doctrine/persistence/pull/342#issuecomment-1972904309 was suggesting, and that also works.

#351 was merged and released last week. So given it fixes same issue we're good to close this one?

2024-03-18 13:55 UTC, mustanggb commented
> #351 was merged and released last week. So given it fixes same issue we're good to close this one?

Ah perfect, yes that should resolve this, good to close I'd say.

2024-03-18 14:53 UTC, malarzm commented
Cool! Thanks @luzrain for your work on this PR!

2024-03-18 14:53 UTC, closed without merging